package org.kimplify.countries.model

enum class Region {
    ANTARCTICA, AUSTRALIA_AND_NEW_ZEALAND, CARIBBEAN, CENTRAL_AMERICA, CENTRAL_ASIA,
    EASTERN_AFRICA, EASTERN_ASIA, EASTERN_EUROPE, MELANESIA, MICRONESIA, MIDDLE_AFRICA,
    NORTHERN_AFRICA, NORTHERN_AMERICA, NORTHERN_EUROPE, POLYNESIA, SOUTH_AMERICA,
    SOUTHEASTERN_ASIA, SOUTHERN_AFRICA, SOUTHERN_ASIA, SOUTHERN_EUROPE,
    WESTERN_AFRICA, WESTERN_ASIA, WESTERN_EUROPE
}
