package com.sebastianfiser.fitnesscoach.models

data class Exercise(
    val name: String,
    val weight: Float,
    val sets: Int,
    val reps: Int,
    var isDone: Boolean = false,
    var isSkipped: Boolean = false
)

data class Day(val day: String, val exercises: List<Exercise>)

data class SetEntry (
    val weight: String,
    val reps: String,
    var isDone: Boolean = false
)

data class ExerciseStat(
    val name: String,
    val pr: Float,
    val weeklyGain: Float
)

val exerciseList = listOf(
    "Bench press",
    "Squats",
    "Deadlift",
    "Overhead press",
    "Incline bench press",
    "Decline bench press",
    "Dumbbell bench press",
    "Close-grip bench press",
    "Floor press",
    "Barbell squat",
    "Back squat",
    "Front squat",
    "Goblet squat",
    "Bulgarian split squat",
    "Split squat",
    "Hack squat",
    "Leg press",
    "Lunges",
    "Walking lunges",
    "Reverse lunges",
    "Step-ups",
    "Romanian deadlift",
    "Stiff-legged deadlift",
    "Conventional deadlift",
    "Sumo deadlift",
    "Trap bar deadlift",
    "Good mornings",
    "Hip thrust",
    "Glute bridge",
    "Kettlebell swing",
    "Single-leg Romanian deadlift",
    "Hamstring curl",
    "Seated hamstring curl",
    "Nordic hamstring curl",
    "Calf raise",
    "Standing calf raise",
    "Seated calf raise",
    "Seated military press",
    "Dumbbell shoulder press",
    "Arnold press",
    "Push press",
    "Pike push-up",
    "Handstand push-up",
    "Lateral raise",
    "Front raise",
    "Rear delt fly",
    "Bent-over lateral raise",
    "Upright row",
    "Barbell shrug",
    "Dumbbell shrug",
    "Bent-over row",
    "Barbell row",
    "Pendlay row",
    "Single-arm dumbbell row",
    "T-bar row",
    "Seal row",
    "Inverted row",
    "Lat pulldown",
    "Pull-up",
    "Chin-up",
    "Neutral-grip pull-up",
    "Weighted pull-up",
    "Wide-grip pull-up",
    "Assisted pull-up",
    "Seated cable row",
    "Face pull",
    "Straight-arm pulldown",
    "Cable pullover",
    "Chest dip",
    "Bench dip",
    "Cable fly",
    "Pec deck fly",
    "Dumbbell fly",
    "Incline dumbbell fly",
    "Push-up",
    "Diamond push-up",
    "Decline push-up",
    "Ring push-up",
    "Triceps pushdown",
    "Overhead triceps extension",
    "Skullcrusher",
    "Triceps kickback",
    "Barbell curl",
    "Dumbbell curl",
    "Hammer curl",
    "Preacher curl",
    "Concentration curl",
    "Cable curl",
    "Reverse curl",
    "Zottman curl",
    "Incline dumbbell curl",
    "Wrist curl",
    "Farmer's walk",
    "Suitcase carry",
    "Kettlebell carry",
    "Overhead carry",
    "Sled push",
    "Sled pull",
    "Battle ropes",
    "Medicine ball slam",
    "Box jump",
    "Depth jump",
    "Plyometric push-up",
    "Broad jump",
    "Tuck jump",
    "Burpee",
    "Mountain climber",
    "High knees",
    "Jump rope",
    "Rowing (erg)",
    "Stationary bike sprint",
    "Sprint (short)",
    "Hill sprint",
    "Agility ladder drills",
    "Cone drills",
    "Bear crawl",
    "Crab walk",
    "Duck walk",
    "Walking plank",
    "Bird dog",
    "Dead bug",
    "Plank",
    "Side plank",
    "Hollow hold",
    "Superman",
    "Back extension",
    "Hyperextension",
    "Russian twist",
    "Bicycle crunch",
    "Sit-up",
    "Hanging leg raise",
    "Lying leg raise",
    "Toe touch",
    "Cable woodchopper",
    "Kettlebell windmill",
    "Turkish get-up",
    "Windshield wipers",
    "Sled drags",
    "Box step-over",
    "Hip abduction",
    "Hip adduction",
    "Clamshell",
    "Fire hydrant",
    "Donkey kick",
    "Glute kickback",
    "Cable pull-through",
    "Single-leg hip thrust",
    "Cossack squat",
    "Jefferson squat",
    "Sots press",
    "Jefferson curl",
    "Kettlebell snatch",
    "Kettlebell clean and press",
    "Power clean",
    "Hang clean",
    "Clean and jerk",
    "Snatch",
    "Push jerk",
    "Split jerk",
    "Thruster",
    "Man maker",
    "Renegade row",
    "Single-leg RDL",
    "Single-leg squat",
    "Medicine ball chest pass",
    "Sled sprint",
    "Incline treadmill walk",
    "Elliptical intervals",
    "Boxing mitt work",
    "Shadow boxing"
)
