name: Android Build

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout projektu
        uses: actions/checkout@v4

      - name: Nastavení Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17' # Většina moderních Android projektů vyžaduje 17+
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Creating local.properities
        run: |
          echo "APPWRITE_ENDPOINT=${{ secrets.APPWRITE_ENDPOINT }}" >> local.properities
          echo "APPWRITE_PROJECT_ID=${{ secrets.APPWRITE_PROJECT_ID }}" >> local.properities

      - name: Build s Gradle
        run: ./gradlew assembleDebug

      - name: Build release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: debug-${{ github.run_number }}-${{ github.sha }}
          name: Debug Build
          files: app/build/outputs/apk/debug/*.apk
          prerelease: true

      - name: Upload APK jako artefakt
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/debug/*.apk